### ISSUE TITLE
OpenSSL plugin does not compile with OpenSSL 1.1.x on Debian 10 (buster)

### ISSUE THREAD

**Issue by bma67** [fillabs/FITSec#3]
gcc is version 8.3.0

Error is:

plugins/fitsec_openssl.c: In function 'OpenSSL_ReadSignature':
plugins/fitsec_openssl.c:246:21: error: dereferencing pointer to incomplete type 'ECDSA_SIG' {aka 'struct ECDSA_SIG_st'}
  BN_bin2bn(s, 32, sg->s);

**Comment by bma67** [comment]
Attached, you will find a proposed patch.
[FITSec_OpenSSL_v1.1.x.patch.txt](https://github.com/fillabs/FITSec/files/4070876/FITSec_OpenSSL_v1.1.x.patch.txt)
